### ISSUE TITLE
Getting Crash from Split IO android client. 

### ISSUE THREAD

**Issue by robmarinaro** [splitio/android-client#90] opened 2019-08-08 17:52 UTC
After implementing Split into our native android app the following crash has started to occur. 

`Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'void java.io.FileOutputStream.close()' on a null object reference
       at io.split.android.client.storage.FileStorage.write + 81(FileStorage.java:81)
       at io.split.android.client.cache.SplitCache.writeSplitsToDisk + 147(SplitCache.java:147)
       at java.lang.reflect.Method.invoke(Method.java)
       at androidx.lifecycle.ClassesInfoCache$MethodReference.invokeCallback + 216(ClassesInfoCache.java:216)
       at androidx.lifecycle.ClassesInfoCache$CallbackInfo.invokeMethodsForEvent + 194(ClassesInfoCache.java:194)
       at androidx.lifecycle.ClassesInfoCache$CallbackInfo.invokeCallbacks + 185(ClassesInfoCache.java:185)
       at androidx.lifecycle.ReflectiveGenericLifecycleObserver.onStateChanged + 36(ReflectiveGenericLifecycleObserver.java:36)
       at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent + 361(LifecycleRegistry.java:361)
       at androidx.lifecycle.LifecycleRegistry.backwardPass + 316(LifecycleRegistry.java:316)
       at androidx.lifecycle.LifecycleRegistry.sync + 334(LifecycleRegistry.java:334)
       at androidx.lifecycle.LifecycleRegistry.moveToState + 145(LifecycleRegistry.java:145)
       at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent + 131(LifecycleRegistry.java:131)
       at androidx.lifecycle.ProcessLifecycleOwner.dispatchPauseIfNeeded + 140(ProcessLifecycleOwner.java:140)
       at androidx.lifecycle.ProcessLifecycleOwner$1.run + 67(ProcessLifecycleOwner.java:67)
       at android.os.Handler.handleCallback + 739(Handler.java:739)
       at android.os.Handler.dispatchMessage + 95(Handler.java:95)
       at android.os.Looper.loop + 158(Looper.java:158)
       at android.app.ActivityThread.main + 7225(ActivityThread.java:7225)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run + 1230(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main + 1120(ZygoteInit.java:1120)`

Seems the problem is in this [method](https://github.com/splitio/android-client/blob/1660d427ab074d30e5fea526924e238466745a38/src/main/java/io/split/android/client/storage/FileStorage.java#L67).

Sometimes, an error occurs during the execution of "new FileOutputStream (file)", which causes the property to remain in the value "fileOutputStream == null". And in the future, we try to execute the code "fileOutputStream.close ();" in finally block, when property equals null. Resulting in a crash with NPE.

**Comment by NicoZelaya** [comment] 2019-08-08 18:59
Hi @robmarinaro! 

Sorry to hear about the inconveniences. Can I ask which version of the SDK are you using on that app? 

The newest version where I can see the `.close()` method being invoked on line 81 of FileStorage.java is on v2.3.0. See: https://github.com/splitio/android-client/blob/2.3.0/src/main/java/io/split/android/client/storage/FileStorage.java#L81

But after that one and up to the current version, we have the null check on that line before trying to execute `close()`. See: https://github.com/splitio/android-client/blob/2.4.1/src/main/java/io/split/android/client/storage/FileStorage.java#L81

If you're running a version <= 2.3.0 I would suggest you try an update as the first step (since it might be the issue we fixed on 2.3.1). If not let us know which version you're using and we'll try to reproduce from our end.

Best regards,
Nico.

**Comment by NicoZelaya** [comment] 2019-09-26 13:41
Closing due to inactivity.

**Closed by NicoZelaya** 2019-09-26 13:41 UTC
